<script>
  export let assets;
  let width = null;
</script>

<!-- Generated by ai2html v0.100.0 - 2021-09-30 14:28 -->

<div id="g-step-3-box" bind:clientWidth="{width}">
  <!-- Artboard: XL -->
  {#if width && width >= 1200}
    <div id="g-step-3-XL" class="g-artboard" style="">
      <div style="padding: 0 0 50% 0;"></div>
      <div
        id="g-step-3-XL-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-XL.png);"
      ></div>
      <div
        id="g-ai0-1"
        class="g-step-3 g-aiAbs g-aiPointText"
        style="top:19.683%;margin-top:-21.1px;left:54.3441%;width:130px;"
      >
        <p class="g-pstyle0">Something</p>
        <p class="g-pstyle0">happened here</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: LG -->
  {#if width && width >= 930 && width < 1200}
    <div id="g-step-3-LG" class="g-artboard" style="">
      <div style="padding: 0 0 55.3763% 0;"></div>
      <div
        id="g-step-3-LG-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-LG.png);"
      ></div>
      <div
        id="g-ai1-1"
        class="g-step-3 g-aiAbs g-aiPointText"
        style="top:27.5682%;margin-top:-21px;left:54.9127%;width:118px;"
      >
        <p class="g-pstyle0">Something</p>
        <p class="g-pstyle0">happened here</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: MD -->
  {#if width && width >= 660 && width < 930}
    <div id="g-step-3-MD" class="g-artboard" style="">
      <div style="padding: 0 0 55.7576% 0;"></div>
      <div
        id="g-step-3-MD-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-MD.png);"
      ></div>
      <div
        id="g-ai2-1"
        class="g-step-3 g-aiAbs g-aiPointText"
        style="top:23.3631%;margin-top:-21px;left:50.4963%;width:118px;"
      >
        <p class="g-pstyle0">Something</p>
        <p class="g-pstyle0">happened here</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: SM -->
  {#if width && width >= 510 && width < 660}
    <div id="g-step-3-SM" class="g-artboard" style="">
      <div style="padding: 0 0 49.6078% 0;"></div>
      <div
        id="g-step-3-SM-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-SM.png);"
      ></div>
      <div
        id="g-ai3-1"
        class="g-step-3 g-aiAbs g-aiPointText"
        style="top:20.1486%;margin-top:-21px;left:55.7925%;width:118px;"
      >
        <p class="g-pstyle0">Something</p>
        <p class="g-pstyle0">happened here</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: XS -->
  {#if width && width >= 0 && width < 510}
    <div id="g-step-3-XS" class="g-artboard" style="">
      <div style="padding: 0 0 55.4545% 0;"></div>
      <div
        id="g-step-3-XS-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-XS.png);"
      ></div>
      <div
        id="g-ai4-1"
        class="g-step-3 g-aiAbs g-aiPointText"
        style="top:42.0634%;margin-top:-21px;left:27.3523%;width:118px;"
      >
        <p class="g-pstyle0">Something</p>
        <p class="g-pstyle0">happened here</p>
      </div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2021-09-30 14:28 -->

<!-- ai file: step-3.ai -->
<style lang="scss">
  #g-step-3-box,
  #g-step-3-box .g-artboard {
    margin: 0 auto;
  }
  #g-step-3-box p {
    margin: 0;
  }
  #g-step-3-box .g-aiAbs {
    position: absolute;
  }
  #g-step-3-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-step-3-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-step-3-XL {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-XL p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 20px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 18px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-XL .g-pstyle0 {
    height: 20px;
  }
  #g-step-3-LG {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-LG p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 20px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-LG .g-pstyle0 {
    height: 20px;
  }
  #g-step-3-MD {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-MD p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 20px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-MD .g-pstyle0 {
    height: 20px;
  }
  #g-step-3-SM {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-SM p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 20px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-SM .g-pstyle0 {
    height: 20px;
  }
  #g-step-3-XS {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-XS p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 20px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-XS .g-pstyle0 {
    height: 20px;
  }

  /* Custom CSS */
</style>
