<script>
  export let assets;
  let width = null;
</script>

<!-- Generated by ai2html v0.100.0 - 2021-09-30 14:21 -->

<div id="g-step-1-box" bind:clientWidth="{width}">
  <!-- Artboard: XL -->
  {#if width && width >= 1200}
    <div id="g-step-1-XL" class="g-artboard" style="">
      <div style="padding: 0 0 50% 0;"></div>
      <div
        id="g-step-1-XL-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-XL.png);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: LG -->
  {#if width && width >= 930 && width < 1200}
    <div id="g-step-1-LG" class="g-artboard" style="">
      <div style="padding: 0 0 55.3763% 0;"></div>
      <div
        id="g-step-1-LG-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-LG.png);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: MD -->
  {#if width && width >= 660 && width < 930}
    <div id="g-step-1-MD" class="g-artboard" style="">
      <div style="padding: 0 0 55.7576% 0;"></div>
      <div
        id="g-step-1-MD-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-MD.png);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: SM -->
  {#if width && width >= 510 && width < 660}
    <div id="g-step-1-SM" class="g-artboard" style="">
      <div style="padding: 0 0 49.6078% 0;"></div>
      <div
        id="g-step-1-SM-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-SM.png);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: XS -->
  {#if width && width >= 0 && width < 510}
    <div id="g-step-1-XS" class="g-artboard" style="">
      <div style="padding: 0 0 55.4545% 0;"></div>
      <div
        id="g-step-1-XS-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-XS.png);"
      ></div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2021-09-30 14:21 -->

<!-- ai file: step-1.ai -->
<style lang="scss">
  #g-step-1-box,
  #g-step-1-box .g-artboard {
    margin: 0 auto;
  }
  #g-step-1-box p {
    margin: 0;
  }
  #g-step-1-box .g-aiAbs {
    position: absolute;
  }
  #g-step-1-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-step-1-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-step-1-XL {
    position: relative;
    overflow: hidden;
  }
  #g-step-1-LG {
    position: relative;
    overflow: hidden;
  }
  #g-step-1-MD {
    position: relative;
    overflow: hidden;
  }
  #g-step-1-SM {
    position: relative;
    overflow: hidden;
  }
  #g-step-1-XS {
    position: relative;
    overflow: hidden;
  }

  /* Custom CSS */
</style>
