<script>
  import { assets } from '$app/paths';
  let width = null;
</script>

<!-- Generated by ai2html v0.100.0 - 2021-09-27 17:45 -->


<div id="g-step-4-box" bind:clientWidth="{width}">
  <!-- Artboard: xs -->
  {#if width && width >= 0 && width < 510}
    <div id="g-step-4-xs" class="g-artboard" style="">
      <div style="padding: 0 0 41.7422% 0;"></div>
      <div
        id="g-step-4-xs-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-4-xs.png);"
      ></div>
      <div
        id="g-ai0-1"
        class="g-art g-aiAbs g-aiPointText"
        style="top:14.6223%;margin-top:-12.1px;left:81.3105%;margin-left:-36px;width:72px;"
      >
        <p class="g-pstyle0">Step 4</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: sm -->
  {#if width && width >= 510 && width < 660}
    <div id="g-step-4-sm" class="g-artboard" style="">
      <div style="padding: 0 0 39.5265% 0;"></div>
      <div
        id="g-step-4-sm-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-4-sm.png);"
      ></div>
      <div
        id="g-ai1-1"
        class="g-art g-aiAbs g-aiPointText"
        style="top:12.5302%;margin-top:-18.3px;left:82.7177%;margin-left:-48.5px;width:97px;"
      >
        <p class="g-pstyle0">Step 4</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: md -->
  {#if width && width >= 660}
    <div id="g-step-4-md" class="g-artboard" style="">
      <div style="padding: 0 0 42.6128% 0;"></div>
      <div
        id="g-step-4-md-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-4-md.png);"
      ></div>
      <div
        id="g-ai2-1"
        class="g-art g-aiAbs g-aiPointText"
        style="top:10.6203%;margin-top:-29.9px;left:83.3201%;margin-left:-71px;width:142px;"
      >
        <p class="g-pstyle0">Step 4</p>
      </div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2021-09-27 17:45 -->

<!-- ai file: step-4.ai -->
<style lang="scss">
  #g-step-4-box,
  #g-step-4-box .g-artboard {
    margin: 0 auto;
  }
  #g-step-4-box p {
    margin: 0;
  }
  #g-step-4-box .g-aiAbs {
    position: absolute;
  }
  #g-step-4-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-step-4-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-step-4-xs {
    position: relative;
    overflow: hidden;
  }
  #g-step-4-xs p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 700;
    line-height: 22px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 19px;
    text-align: left;
    color: rgb(106, 81, 163);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-4-xs .g-pstyle0 {
    height: 22px;
    text-align: center;
  }
  #g-step-4-sm {
    position: relative;
    overflow: hidden;
  }
  #g-step-4-sm p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 700;
    line-height: 33px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 28px;
    text-align: left;
    color: rgb(106, 81, 163);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-4-sm .g-pstyle0 {
    height: 33px;
    text-align: center;
  }
  #g-step-4-md {
    position: relative;
    overflow: hidden;
  }
  #g-step-4-md p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 700;
    line-height: 53px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 44px;
    text-align: left;
    color: rgb(106, 81, 163);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-4-md .g-pstyle0 {
    height: 53px;
    text-align: center;
  }

  /* Custom CSS */
</style>
