<script>
  import { assets } from '$app/paths';
  let width = null;
</script>

<!-- Generated by ai2html v0.100.0 - 2021-09-23 14:02 -->


<div id="g-step-1-box" bind:clientWidth="{width}">
  <!-- Artboard: xs -->
  {#if width && width >= 0 && width < 510}
    <div id="g-step-1-xs" class="g-artboard" style="">
      <div style="padding: 0 0 176.8364% 0;"></div>
      <div
        id="g-step-1-xs-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-xs.png);"
      ></div>
      <div
        id="g-ai0-1"
        class="g-art g-aiAbs g-aiPointText"
        style="top:21.8413%;margin-top:-56.5px;left:37.8816%;margin-left:-100px;width:200px;"
      >
        <p class="g-pstyle0">Ai2svelte</p>
        <p class="g-pstyle0">step 1</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: sm -->
  {#if width && width >= 510 && width < 660}
    <div id="g-step-1-sm" class="g-artboard" style="">
      <div style="padding: 0 0 39.5265% 0;"></div>
      <div
        id="g-step-1-sm-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-sm.png);"
      ></div>
      <div
        id="g-ai1-1"
        class="g-art g-aiAbs g-aiPointText"
        style="top:53.73%;margin-top:-40.3px;left:16.2846%;margin-left:-75px;width:150px;"
      >
        <p class="g-pstyle0">Ai2svelte</p>
        <p class="g-pstyle0">step 1</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: md -->
  {#if width && width >= 660}
    <div id="g-step-1-md" class="g-artboard" style="">
      <div style="padding: 0 0 42.6128% 0;"></div>
      <div
        id="g-step-1-md-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-1-md.png);"
      ></div>
      <div
        id="g-ai2-1"
        class="g-art g-aiAbs g-aiPointText"
        style="top:50.6523%;margin-top:-56.5px;left:17.1816%;margin-left:-100px;width:200px;"
      >
        <p class="g-pstyle0">Ai2svelte</p>
        <p class="g-pstyle0">step 1</p>
      </div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2021-09-23 14:02 -->

<!-- ai file: step-1.ai -->
<style lang="scss">
  #g-step-1-box,
  #g-step-1-box .g-artboard {
    margin: 0 auto;
  }
  #g-step-1-box p {
    margin: 0;
  }
  #g-step-1-box .g-aiAbs {
    position: absolute;
  }
  #g-step-1-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-step-1-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-step-1-xs {
    position: relative;
    overflow: hidden;
  }
  #g-step-1-xs p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 700;
    line-height: 53px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 44px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-1-xs .g-pstyle0 {
    height: 53px;
    text-align: center;
  }
  #g-step-1-sm {
    position: relative;
    overflow: hidden;
  }
  #g-step-1-sm p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 700;
    line-height: 38px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 32px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-1-sm .g-pstyle0 {
    height: 38px;
    text-align: center;
  }
  #g-step-1-md {
    position: relative;
    overflow: hidden;
  }
  #g-step-1-md p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 700;
    line-height: 53px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 44px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-1-md .g-pstyle0 {
    height: 53px;
    text-align: center;
  }

  /* Custom CSS */
</style>
