<script>
  export let assets = '';
  let width = null;
</script>

<!-- Generated by ai2html v0.100.0 - 2021-09-29 14:28 -->

<div id="g-step-3-box" bind:clientWidth="{width}">
  <!-- Artboard: xs -->
  {#if width && width >= 0 && width < 510}
    <div id="g-step-3-xs" class="g-artboard" style="">
      <div style="padding: 0 0 136.3636% 0;"></div>
      <div
        id="g-step-3-xs-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-xs.png);"
      ></div>
      <div
        id="g-ai0-1"
        class="g-ward_15 g-aiAbs g-aiPointText"
        style="top:34.58%;margin-top:-6.6px;left:36.6208%;width:80px;"
      >
        <p class="g-pstyle0">15TH WARD</p>
      </div>
      <div
        id="g-ai0-2"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:36.2183%;margin-top:-9px;left:28.0957%;margin-left:-38px;width:76px;"
      >
        <p class="g-pstyle1">DOWNTOWN</p>
      </div>
      <div
        id="g-ai0-3"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:44.6334%;margin-top:-13.9px;left:54.5667%;margin-left:-36.5px;width:73px;"
      >
        <p class="g-pstyle2">Syracuse</p>
        <p class="g-pstyle2">University</p>
      </div>
      <div
        id="g-ai0-4"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:97.5377%;margin-top:-7.9px;left:85.4058%;margin-left:-21.5px;width:43px;"
      >
        <p class="g-pstyle3">1 MILE</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: sm -->
  {#if width && width >= 510 && width < 660}
    <div id="g-step-3-sm" class="g-artboard" style="">
      <div style="padding: 0 0 100% 0;"></div>
      <div
        id="g-step-3-sm-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-sm.png);"
      ></div>
      <div
        id="g-ai1-1"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:7.1906%;margin-top:-5.7px;left:8.5527%;margin-left:-46.5px;width:93px;"
      >
        <p class="g-pstyle0">Onondaga Lake</p>
      </div>
      <div
        id="g-ai1-2"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:9.0161%;margin-top:-9px;left:49.9835%;margin-left:-37px;width:74px;"
      >
        <p class="g-pstyle1">NORTHSIDE</p>
      </div>
      <div
        id="g-ai1-3"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:18.4279%;margin-top:-9px;left:81.5529%;margin-left:-36px;width:72px;"
      >
        <p class="g-pstyle1">EASTWOOD</p>
      </div>
      <div
        id="g-ai1-4"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:20.9769%;margin-top:-9px;left:22.1104%;margin-left:-37.5px;width:75px;"
      >
        <p class="g-pstyle1">LAKEFRONT</p>
      </div>
      <div
        id="g-ai1-5"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:25.4867%;margin-top:-9px;left:52.9609%;margin-left:-51px;width:102px;"
      >
        <p class="g-pstyle1">NEAR NORTHEAST</p>
      </div>
      <div
        id="g-ai1-6"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:34.8985%;margin-top:-9px;left:9.1263%;margin-left:-47px;width:94px;"
      >
        <p class="g-pstyle1">TIPPERARY HILL</p>
      </div>
      <div
        id="g-ai1-7"
        class="g-ward_15 g-aiAbs g-aiPointText"
        style="top:36.6317%;margin-top:-4.8px;left:44.6565%;width:67px;"
      >
        <p class="g-pstyle2">15TH WARD</p>
      </div>
      <div
        id="g-ai1-8"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:38.82%;margin-top:-9px;left:41.091%;margin-left:-38px;width:76px;"
      >
        <p class="g-pstyle1">DOWNTOWN</p>
      </div>
      <div
        id="g-ai1-9"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:44.3102%;margin-top:-9px;left:74.8083%;margin-left:-38.5px;width:77px;"
      >
        <p class="g-pstyle1">SCOTTHOLM</p>
      </div>
      <div
        id="g-ai1-10"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:46.5946%;margin-top:-15.6px;left:57.0473%;margin-left:-36.5px;width:73px;"
      >
        <p class="g-pstyle3">Syracuse</p>
        <p class="g-pstyle3">University</p>
      </div>
      <div
        id="g-ai1-11"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:60.1926%;margin-top:-9px;left:39.4475%;margin-left:-37px;width:74px;"
      >
        <p class="g-pstyle1">SOUTHSIDE</p>
      </div>
      <div
        id="g-ai1-12"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:96.6553%;margin-top:-8.9px;left:88.569%;margin-left:-22.5px;width:45px;"
      >
        <p class="g-pstyle4">1 MILE</p>
      </div>
      <div
        id="g-ai1-13"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:96.8593%;margin-top:-9px;left:44.653%;margin-left:-27px;width:54px;"
      >
        <p class="g-pstyle1">VALLEY</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: md -->
  {#if width && width >= 660 && width < 930}
    <div id="g-step-3-md" class="g-artboard" style="">
      <div style="padding: 0 0 81.8182% 0;"></div>
      <div
        id="g-step-3-md-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-md.png);"
      ></div>
      <div
        id="g-ai2-1"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:9.7682%;margin-top:-5.7px;left:15.8152%;margin-left:-47px;width:94px;"
      >
        <p class="g-pstyle0">Onondaga Lake</p>
      </div>
      <div
        id="g-ai2-2"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:11.4906%;margin-top:-9px;left:49.8154%;margin-left:-37.5px;width:75px;"
      >
        <p class="g-pstyle1">NORTHSIDE</p>
      </div>
      <div
        id="g-ai2-3"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:20.5646%;margin-top:-9px;left:74.5399%;margin-left:-36.5px;width:73px;"
      >
        <p class="g-pstyle1">EASTWOOD</p>
      </div>
      <div
        id="g-ai2-4"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:22.9721%;margin-top:-9px;left:27.9863%;margin-left:-38px;width:76px;"
      >
        <p class="g-pstyle1">LAKEFRONT</p>
      </div>
      <div
        id="g-ai2-5"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:27.2313%;margin-top:-9px;left:52.1942%;margin-left:-52px;width:104px;"
      >
        <p class="g-pstyle1">NEAR NORTHEAST</p>
      </div>
      <div
        id="g-ai2-6"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:36.3054%;margin-top:-9px;left:17.7989%;margin-left:-47.5px;width:95px;"
      >
        <p class="g-pstyle1">TIPPERARY HILL</p>
      </div>
      <div
        id="g-ai2-7"
        class="g-ward_15 g-aiAbs g-aiPointText"
        style="top:38.1259%;margin-top:-4.9px;left:45.6208%;width:67px;"
      >
        <p class="g-pstyle2">15TH WARD</p>
      </div>
      <div
        id="g-ai2-8"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:39.6387%;margin-top:-9px;left:42.7816%;margin-left:-38.5px;width:77px;"
      >
        <p class="g-pstyle1">DOWNTOWN</p>
      </div>
      <div
        id="g-ai2-9"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:45.3795%;margin-top:-9px;left:69.2528%;margin-left:-39px;width:78px;"
      >
        <p class="g-pstyle1">SCOTTHOLM</p>
      </div>
      <div
        id="g-ai2-10"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:47.3578%;margin-top:-15.7px;left:55.7844%;margin-left:-36.5px;width:73px;"
      >
        <p class="g-pstyle3">Syracuse</p>
        <p class="g-pstyle3">University</p>
      </div>
      <div
        id="g-ai2-11"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:60.0091%;margin-top:-9px;left:42.1938%;margin-left:-37.5px;width:75px;"
      >
        <p class="g-pstyle1">SOUTHSIDE</p>
      </div>
      <div
        id="g-ai2-12"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:95.7498%;margin-top:-9px;left:45.6613%;margin-left:-27.5px;width:55px;"
      >
        <p class="g-pstyle1">VALLEY</p>
      </div>
      <div
        id="g-ai2-13"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:97.7794%;margin-top:-9px;left:92.1796%;margin-left:-23px;width:46px;"
      >
        <p class="g-pstyle4">1 MILE</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: lg -->
  {#if width && width >= 930 && width < 1200}
    <div id="g-step-3-lg" class="g-artboard" style="">
      <div style="padding: 0 0 67.7419% 0;"></div>
      <div
        id="g-step-3-lg-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-lg.png);"
      ></div>
      <div
        id="g-ai3-1"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:9.5076%;margin-top:-7.9px;left:16.8348%;margin-left:-54px;width:108px;"
      >
        <p class="g-pstyle0">Onondaga Lake</p>
      </div>
      <div
        id="g-ai3-2"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:9.4846%;margin-top:-12.8px;left:49.7993%;margin-left:-36px;width:72px;"
      >
        <p class="g-pstyle1">NORTHSIDE</p>
      </div>
      <div
        id="g-ai3-3"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:20.4143%;margin-top:-12.6px;left:74.4864%;margin-left:-39px;width:78px;"
      >
        <p class="g-pstyle2">EASTWOOD</p>
      </div>
      <div
        id="g-ai3-4"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:23.4301%;margin-top:-12.6px;left:27.9108%;margin-left:-40.5px;width:81px;"
      >
        <p class="g-pstyle2">LAKEFRONT</p>
      </div>
      <div
        id="g-ai3-5"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:28.5095%;margin-top:-12.6px;left:50.6515%;margin-left:-56.5px;width:113px;"
      >
        <p class="g-pstyle2">NEAR NORTHEAST</p>
      </div>
      <div
        id="g-ai3-6"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:39.4619%;margin-top:-12.6px;left:17.7768%;margin-left:-51.5px;width:103px;"
      >
        <p class="g-pstyle2">TIPPERARY HILL</p>
      </div>
      <div
        id="g-ai3-7"
        class="g-ward_15 g-aiAbs g-aiPointText"
        style="top:41.4557%;margin-top:-7.2px;left:45.6208%;width:86px;"
      >
        <p class="g-pstyle3">15TH WARD</p>
      </div>
      <div
        id="g-ai3-8"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:42.9539%;margin-top:-12.6px;left:42.1991%;margin-left:-41.5px;width:83px;"
      >
        <p class="g-pstyle2">DOWNTOWN</p>
      </div>
      <div
        id="g-ai3-9"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:50.4143%;margin-top:-12.6px;left:69.2257%;margin-left:-42px;width:84px;"
      >
        <p class="g-pstyle2">SCOTTHOLM</p>
      </div>
      <div
        id="g-ai3-10"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:52.6752%;margin-top:-18.9px;left:54.2361%;margin-left:-40.5px;width:81px;"
      >
        <p class="g-pstyle4">Syracuse</p>
        <p class="g-pstyle4">University</p>
      </div>
      <div
        id="g-ai3-11"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:67.8746%;margin-top:-12.6px;left:42.1244%;margin-left:-40.5px;width:81px;"
      >
        <p class="g-pstyle2">SOUTHSIDE</p>
      </div>
      <div
        id="g-ai3-12"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:96.1394%;margin-top:-12.7px;left:10.5457%;margin-left:-26.5px;width:53px;"
      >
        <p class="g-pstyle5">1 MILE</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: xl -->
  {#if width && width >= 1200}
    <div id="g-step-3-xl" class="g-artboard" style="">
      <div style="padding: 0 0 52.6667% 0;"></div>
      <div
        id="g-step-3-xl-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/step-3-xl.png);"
      ></div>
      <div
        id="g-ai4-1"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:1.9258%;margin-top:-16.2px;left:49.7008%;margin-left:-43.5px;width:87px;"
      >
        <p class="g-pstyle0">NORTHSIDE</p>
      </div>
      <div
        id="g-ai4-2"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:6.0202%;margin-top:-10px;left:17.5967%;margin-left:-61px;width:122px;"
      >
        <p class="g-pstyle1">Onondaga Lake</p>
      </div>
      <div
        id="g-ai4-3"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:16.3245%;margin-top:-16.2px;left:74.5487%;margin-left:-42px;width:84px;"
      >
        <p class="g-pstyle0">EASTWOOD</p>
      </div>
      <div
        id="g-ai4-4"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:20.122%;margin-top:-16.2px;left:27.6735%;margin-left:-43.5px;width:87px;"
      >
        <p class="g-pstyle0">LAKEFRONT</p>
      </div>
      <div
        id="g-ai4-5"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:26.7675%;margin-top:-16.2px;left:50.5391%;margin-left:-61px;width:122px;"
      >
        <p class="g-pstyle0">NEAR NORTHEAST</p>
      </div>
      <div
        id="g-ai4-6"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:40.8498%;margin-top:-16.2px;left:17.4645%;margin-left:-55.5px;width:111px;"
      >
        <p class="g-pstyle0">TIPPERARY HILL</p>
      </div>
      <div
        id="g-ai4-7"
        class="g-ward_15 g-aiAbs g-aiPointText"
        style="top:43.4104%;margin-top:-9.4px;left:45.4929%;width:103px;"
      >
        <p class="g-pstyle2">15TH WARD</p>
      </div>
      <div
        id="g-ai4-8"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:46.0713%;margin-top:-16.2px;left:42.5673%;margin-left:-44.5px;width:89px;"
      >
        <p class="g-pstyle0">DOWNTOWN</p>
      </div>
      <div
        id="g-ai4-9"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:56.1478%;margin-top:-18.9px;left:53.5115%;margin-left:-40.5px;width:81px;"
      >
        <p class="g-pstyle3">Syracuse</p>
        <p class="g-pstyle3">University</p>
      </div>
      <div
        id="g-ai4-10"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:54.9321%;margin-top:-16.2px;left:69.2283%;margin-left:-45px;width:90px;"
      >
        <p class="g-pstyle0">SCOTTHOLM</p>
      </div>
      <div
        id="g-ai4-11"
        class="g-neighborhoods g-aiAbs g-aiPointText"
        style="top:77.8751%;margin-top:-16.2px;left:43.7014%;margin-left:-43.5px;width:87px;"
      >
        <p class="g-pstyle0">SOUTHSIDE</p>
      </div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2021-09-29 14:28 -->

<!-- ai file: step-3.ai -->
<style lang="scss">
  #g-step-3-box,
  #g-step-3-box .g-artboard {
    margin: 0 auto;
  }
  #g-step-3-box p {
    margin: 0;
  }
  #g-step-3-box .g-aiAbs {
    position: absolute;
  }
  #g-step-3-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-step-3-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-step-3-xs {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-xs p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 13px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-xs .g-pstyle0 {
    line-height: 12px;
    height: 12px;
    letter-spacing: 0.1em;
    font-size: 10px;
  }
  #g-step-3-xs .g-pstyle1 {
    line-height: 17px;
    height: 17px;
    letter-spacing: 0.1em;
    font-size: 9px;
    text-align: center;
    color: rgb(153, 153, 153);
  }
  #g-step-3-xs .g-pstyle2 {
    height: 13px;
    text-align: center;
  }
  #g-step-3-xs .g-pstyle3 {
    font-style: italic;
    line-height: 15px;
    height: 15px;
    font-size: 8px;
    text-align: center;
    color: rgb(102, 102, 102);
  }
  #g-step-3-sm {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-sm p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 17px;
    height: auto;
    opacity: 1;
    letter-spacing: 0.1em;
    font-size: 9px;
    text-align: left;
    color: rgb(153, 153, 153);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-sm .g-pstyle0 {
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-style: italic;
    line-height: 10px;
    height: 10px;
    letter-spacing: 0em;
    font-size: 10px;
    text-align: center;
    color: rgb(0, 0, 0);
  }
  #g-step-3-sm .g-pstyle1 {
    height: 17px;
    text-align: center;
  }
  #g-step-3-sm .g-pstyle2 {
    line-height: 9px;
    height: 9px;
    font-size: 8px;
    color: rgb(0, 0, 0);
  }
  #g-step-3-sm .g-pstyle3 {
    line-height: 15px;
    height: 15px;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: center;
    color: rgb(0, 0, 0);
  }
  #g-step-3-sm .g-pstyle4 {
    font-style: italic;
    height: 17px;
    letter-spacing: 0em;
    text-align: center;
    color: rgb(102, 102, 102);
  }
  #g-step-3-md {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-md p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 17px;
    height: auto;
    opacity: 1;
    letter-spacing: 0.1em;
    font-size: 9px;
    text-align: left;
    color: rgb(153, 153, 153);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-md .g-pstyle0 {
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-style: italic;
    line-height: 10px;
    height: 10px;
    letter-spacing: 0em;
    font-size: 10px;
    text-align: center;
    color: rgb(0, 0, 0);
  }
  #g-step-3-md .g-pstyle1 {
    height: 17px;
    text-align: center;
  }
  #g-step-3-md .g-pstyle2 {
    line-height: 9px;
    height: 9px;
    font-size: 8px;
    color: rgb(0, 0, 0);
  }
  #g-step-3-md .g-pstyle3 {
    line-height: 15px;
    height: 15px;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: center;
    color: rgb(0, 0, 0);
  }
  #g-step-3-md .g-pstyle4 {
    font-style: italic;
    height: 17px;
    letter-spacing: 0em;
    text-align: center;
    color: rgb(102, 102, 102);
  }
  #g-step-3-lg {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-lg p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 24px;
    height: auto;
    opacity: 1;
    letter-spacing: 0.1em;
    font-size: 10px;
    text-align: left;
    color: rgb(153, 153, 153);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-lg .g-pstyle0 {
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-style: italic;
    line-height: 14px;
    height: 14px;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: center;
    color: rgb(0, 0, 0);
  }
  #g-step-3-lg .g-pstyle1 {
    height: 24px;
    font-size: 8px;
    text-align: center;
  }
  #g-step-3-lg .g-pstyle2 {
    height: 24px;
    text-align: center;
  }
  #g-step-3-lg .g-pstyle3 {
    line-height: 13px;
    height: 13px;
    font-size: 11px;
    color: rgb(0, 0, 0);
  }
  #g-step-3-lg .g-pstyle4 {
    line-height: 18px;
    height: 18px;
    letter-spacing: 0em;
    font-size: 14px;
    text-align: center;
    color: rgb(0, 0, 0);
  }
  #g-step-3-lg .g-pstyle5 {
    font-style: italic;
    height: 24px;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: center;
    color: rgb(102, 102, 102);
  }
  #g-step-3-xl {
    position: relative;
    overflow: hidden;
  }
  #g-step-3-xl p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 31px;
    height: auto;
    opacity: 1;
    letter-spacing: 0.1em;
    font-size: 11px;
    text-align: left;
    color: rgb(153, 153, 153);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-step-3-xl .g-pstyle0 {
    height: 31px;
    text-align: center;
  }
  #g-step-3-xl .g-pstyle1 {
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-style: italic;
    line-height: 18px;
    height: 18px;
    letter-spacing: 0em;
    font-size: 14px;
    text-align: center;
    color: rgb(0, 0, 0);
  }
  #g-step-3-xl .g-pstyle2 {
    line-height: 17px;
    height: 17px;
    font-size: 14px;
    color: rgb(0, 0, 0);
  }
  #g-step-3-xl .g-pstyle3 {
    line-height: 18px;
    height: 18px;
    letter-spacing: 0em;
    font-size: 14px;
    text-align: center;
    color: rgb(0, 0, 0);
  }

  /* Custom CSS */
</style>
